Sdrm.Web/Controllers/DiscussionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sdrm.Core.Entities;
using Sdrm.Infrastructure;
using Sdrm.Web.Models;
using static Sdrm.Web.Enums.Notification;

namespace Sdrm.Web.Controllers
{
    public class DiscussionsController : BaseController
    {
        #region Properties
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;
        #endregion

        public DiscussionsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Discussions
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Discussions.Include(d => d.Location);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Discussions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var discussion = await _context.Discussions
                .Include(d => d.Location)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (discussion == null)
            {
                return NotFound();
            }

            return View(discussion);
        }

        // GET: Discussions/Create
        public IActionResult Create()
        {
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Name");
            return View();
        }

        // POST: Discussions/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Date,Subject,LocationId")] Discussion discussion)
        {
            if (ModelState.IsValid)
            {
                _context.Add(discussion);
                
                if(await _context.SaveChangesAsync() > 0 )
                {
                    Alert("Success!", "New safety discussion is added.", AlertType.success);
                }
                else
                {
                    Alert("Error!", "Failed to save safety discussion.", AlertType.error);
                    return View(discussion);
                }


                return RedirectToAction(nameof(Edit), new { id = discussion.Id });
            }

            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Name", discussion.LocationId);
            return View(discussion);
        }

        // GET: Discussions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var discussion = await _context.Discussions.FindAsync(id);

            if (discussion == null)
            {
                return NotFound();
            }

            var locations = new SelectList(await _context.Locations.ToListAsync(), "Id", "Name");

            var administratorsInRole = await _userManager.GetUsersInRoleAsync("Administrator");

            var attendee = new SelectList(_userManager.Users.AsEnumerable()
                .Except(administratorsInRole)
                .Select(a => new
                {
                    a.Id,
                    FullName = string.Concat($"{a.Firstname} {a.MiddleName} {a.Lastname}")
                }), "Id", "FullName");

            var attendees = await _context.DiscussionAttendees.Where(a => a.DiscussionId == id).Include( a => a.Attendee).ToListAsync();

            var outcomes = await _context.DiscussionOutcomes.Where(o => o.DiscussionId == id).ToListAsync();

            var discussionsModel = new DiscussionViewModel()
            {
                Id = discussion.Id,
                Date = discussion.Date,
                Subject = discussion.Subject,
                LocationId = discussion.LocationId,
                Locations = locations,
                Attendee = attendee,
                Attendees = attendees,
                Outcomes = outcomes,
                Summary = discussion.Summary
            };

            //ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Name", discussion.LocationId);
            return View(discussionsModel);
        }

        // POST: Discussions/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,Subject,LocationId, Summary")] Discussion discussion)
        {
            if (id != discussion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(discussion);
                    if(await _context.SaveChangesAsync() > 0)
                    {
                        Alert("Success!", "Safety discussion is updated.", AlertType.success);
                    }
                    else
                    {
                        Alert("Error!", "Failed to update safety discussion.", AlertType.error);
                    }

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DiscussionExists(discussion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Edit), new { id = discussion.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveAttendee(int id, [Bind("Id,AttendeeId")] DiscussionViewModel discussion)
        {
            if (id != discussion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var checkExistingAttendee = await _context.DiscussionAttendees.Where(a => a.AttendeeId == discussion.AttendeeId).FirstOrDefaultAsync();

                    if (checkExistingAttendee != null)
                    {
                        Alert("Error!", "Attendee is already registered", AlertType.error);
                        return RedirectToAction(nameof(Edit), new { id = discussion.Id });
                    }


                    var attendee = new DiscussionAttendee() 
                    {
                        DiscussionId = discussion.Id,
                        AttendeeId = discussion.AttendeeId
                    };
                    
                    _context.Update(attendee);
                    if(await _context.SaveChangesAsync() > 0)
                    {
                        Alert("Success!", "New attendee is added.", AlertType.success);
                    }
                    else
                    {
                        Alert("Error!", "Failed to add attendee.", AlertType.error);
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DiscussionExists(discussion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Edit), new { id = discussion.Id });
            }

            return RedirectToAction(nameof(Edit), new { id = discussion.Id });
        }

        // GET: Discussions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var discussion = await _context.Discussions
                .Include(d => d.Location)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (discussion == null)
            {
                return NotFound();
            }

            return View(discussion);
        }

        // POST: Discussions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var discussion = await _context.Discussions.FindAsync(id);
            _context.Discussions.Remove(discussion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAttendee(int id)
        {
            var attendee = await _context.DiscussionAttendees.FindAsync(id);

            if (attendee == null)
            {
                Alert("Error!", "Attendee does not exist.", AlertType.error);
                return RedirectToAction(nameof(Edit), new { id = attendee.DiscussionId });
            }

            try
            {
                _context.DiscussionAttendees.Remove(attendee);
                if (await _context.SaveChangesAsync() > 0)
                {
                    Alert("Success!", "Attendee is removed successfully.", AlertType.success);
                }
            }
            catch (Exception ex)
            {

                Alert("Error!", "Attendee does not exist. Exception: " + ex.Message, AlertType.error);
            }

            return RedirectToAction(nameof(Edit), new { id = attendee.DiscussionId });
        }

        private bool DiscussionExists(int id)
        {
            return _context.Discussions.Any(e => e.Id == id);
        }
    }
}

Sdrm.Web/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sdrm.Core.Entities;
using Sdrm.Infrastructure;

namespace Sdrm.Web.Controllers
{
    public class LocationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LocationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Locations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Locations.ToListAsync());
        }

        // GET: Locations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var location = await _context.Locations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (location == null)
            {
                return NotFound();
            }

            return View(location);
        }

        // GET: Locations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Location location)
        {
            if (ModelState.IsValid)
            {
                _context.Add(location);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(location);
        }

        // GET: Locations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var location = await _context.Locations.FindAsync(id);
            if (location == null)
            {
                return NotFound();
            }
            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Location location)
        {
            if (id != location.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(location);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocationExists(location.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(location);
        }

        // GET: Locations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var location = await _context.Locations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (location == null)
            {
                return NotFound();
            }

            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var location = await _context.Locations.FindAsync(id);
            _context.Locations.Remove(location);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LocationExists(int id)
        {
            return _context.Locations.Any(e => e.Id == id);
        }
    }
}

Sdrm.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Sdrm.Core.Entities

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Safety Discussion Record Management" />
    <meta name="author" content="Sophia Anne Marie P. Dizon" />

    <title>Safety Discussion - @ViewData["Title"]</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-sweetalert/sweetalert.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/lib/bootstrap-sweetalert/sweetalert.js"></script>
</head>
<body>
    @if (SignInManager.IsSignedIn(User))
    {
        <header>
            <nav class="navbar navbar-expand-md navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/images/safety-icon.png" class="d-inline-block align-top" height="30" /> 
                        Safety Discussion
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-md-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ApplicationUsers" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Discussions" asp-action="Index">Discussions</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Locations" asp-action="Index">Locations</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    }
<div class="container">
    <div>
        <h2 class="mt-5">@RenderSection("PageTitle", false)</h2>
        <small>@RenderSection("PageDescription", false)</small>
    </div>
    <hr />
    <main role="main" class="pb-3">
        <partial name="_NotificationPartial" />
        @RenderBody()
    </main>
</div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <small>All rights reserved &copy; 2020 - Security Discussion Record Management</small>
            <small class="float-right"><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy Policy</a></small>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="~/lib/font-awesome/js/all.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Sdrm.Web/Views/Shared/_NotificationPartial.cshtml
@if (TempData["notification"] != null)
{
    @Html.Raw(TempData["notification"])
}